# jaeger/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger-agent
          image: jaegertracing/all-in-one:1.21
          ports:
            - containerPort: 5775
            - containerPort: 6831

