# grafana/values.yaml

adminPassword: 'admin'
persistence:
  enabled: true
  size: 10Gi
  storageClassName: "standard"
  accessMode: ReadWriteOnce
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server:9090
        isDefault: true

